### ISSUE TITLE
Quick XGB question

### ISSUE THREAD

**Issue by david-dirring** [hernanescu/vertex-pipelines-kfp-chicago#2]
Hi, is there a reason that you seemed to go down the XGB route, but decided against it (I can see some XGB lines commented out).  
I was thinking you likely thought it was not needed to illustrate what you wanted?  or was there another reason (like it didn't work)? thanks!

**Comment by hernanescu** [comment]
I had several difficulties when formatting the data for the XGB Model (is not as easy as GCP tells you) so I dropped it out for the time being. It's actually one of the things I'd like to incorporate for the next iteration, but who's got the time? =)

I'm curious to know if this helped you at least a bit, since reaching to this point for me it was a personal hell :P. Feel free to add me on Linkedin or write me at hernanescu@gmail.com. Have a great day!

**Comment by david-dirring** [comment]
yes, absolutely! 

the way you set up the process with the separate process to generate the component yaml files helped me to think about the design of my processes, but also to understand how those are the driving force and vertex orchestrates those files to run easily and with some flexibility. 

I have not been able to get batch predict to work on my XGB process, so it makes me feel better that someone else ran into similar issues.
